mongodb:
  uri: "mongodb://dwc2json:VLWQ8Bke65L52hfBM635@192.168.1.10:27017/?authSource=admin"
  database: "dwc2json"
  collection: "ocorrencias"
  filter: { kingdom: "Plantae" }

local_db:
  type: "duckdb"
  path: "./data/canonicalEntities.db"

processing:
  batch_size: 10000
  confidence_threshold: 0.70

algorithms:
  similarity_weights:
    levenshtein: 0.4
    jaro_winkler: 0.4
    phonetic: 0.2

output:
  csv_path: "./output/canonical_report.csv"
  rules_doc: "./docs/rules.md"
